"""Real initial migration

Revision ID: f9520363ecac
Revises:
Create Date: 2026-04-19 23:26:22.075376

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9520363ecac"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("thread_id", sa.String(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("vote", sa.String(length=8), nullable=False),
        sa.Column("answer_confidence", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("thread_id", "message_id", "user_id", "vote", name="uq_feedback_event_replay_guard"),
    )
    op.create_index(op.f("ix_feedback_events_chat_id"), "feedback_events", ["chat_id"], unique=False)
    op.create_index(op.f("ix_feedback_events_message_id"), "feedback_events", ["message_id"], unique=False)
    op.create_index(op.f("ix_feedback_events_thread_id"), "feedback_events", ["thread_id"], unique=False)
    op.create_index(op.f("ix_feedback_events_user_id"), "feedback_events", ["user_id"], unique=False)
    op.create_table(
        "ingest_jobs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("celery_task_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("current_stage", sa.String(), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingest_jobs_source_id"), "ingest_jobs", ["source_id"], unique=False)
    op.create_table(
        "knowledge_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fact", sa.Text(), nullable=False),
        sa.Column("topic", sa.String(length=256), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_refs", sa.Text(), nullable=False),
        sa.Column("status", sa.Enum("PUBLISHED", "PENDING", "REJECTED", name="knowledgestatus"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("type", sa.Enum("TELEGRAM", "PDF", name="sourcetype"), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column(
            "status", sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="ingeststatus"), nullable=False
        ),
        sa.Column("messages_count", sa.Integer(), nullable=True),
        sa.Column("chunks_indexed", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "telegram_users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "EMPLOYEE", name="userrole"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("telegram_users")
    op.drop_table("sources")
    op.drop_table("knowledge_items")
    op.drop_index(op.f("ix_ingest_jobs_source_id"), table_name="ingest_jobs")
    op.drop_table("ingest_jobs")
    op.drop_index(op.f("ix_feedback_events_user_id"), table_name="feedback_events")
    op.drop_index(op.f("ix_feedback_events_thread_id"), table_name="feedback_events")
    op.drop_index(op.f("ix_feedback_events_message_id"), table_name="feedback_events")
    op.drop_index(op.f("ix_feedback_events_chat_id"), table_name="feedback_events")
    op.drop_table("feedback_events")
    # ### end Alembic commands ###
